// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADz0DsXZcscjAzTwSvi0BTyjt-H_pa1gA',
    appId: '1:918727185493:web:186ba7a2cd3dad2d33b0dc',
    messagingSenderId: '918727185493',
    projectId: 'reddit-a76d4',
    authDomain: 'reddit-a76d4.firebaseapp.com',
    storageBucket: 'reddit-a76d4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqpTbBOOPziUQ0zKXkwkAW_1jXkAbBT_U',
    appId: '1:918727185493:android:8d5d93d23b7d543233b0dc',
    messagingSenderId: '918727185493',
    projectId: 'reddit-a76d4',
    storageBucket: 'reddit-a76d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuM3mfu8wRuUDXmwDjevhhue7bbBxKOoI',
    appId: '1:918727185493:ios:0a19f7f023e0af2133b0dc',
    messagingSenderId: '918727185493',
    projectId: 'reddit-a76d4',
    storageBucket: 'reddit-a76d4.appspot.com',
    iosBundleId: 'com.osmanabdelsalam.redditClone',
  );
}
